import Head from 'next/head'
import Image from 'next/image'
import Hero from '../Components/Hero'
// import styles from '../styles/Home.module.css'



export default function Home() {
    return (
        <div>
            <Head>
                <title>Gordon King Photography</title>
                <meta name="Gordon King Photography" content="Generated by create next app" />
                <link rel="icon" href="favicon.ico?v=1.1" />
            </Head>
            <Hero />

            <p>
                yeah
            </p>
            <p>
                yeah
            </p>
            <p>
                yeah
            </p>
            <p>
                yeah
            </p>
            <p>
                yeah
            </p>
            <p>
                yeah
            </p>
            <p>
                yeah
            </p>
            <p>
                yeah
            </p>

            {/* <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer> */}
        </div>
    )
}
